AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack to build primary DynamoDB Table for ConversationRelay Application

Parameters:
  CurrentEnvironment:
    Type: String
    Default: 'DEV'

Resources:
  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TimeToLiveSpecification:
        AttributeName: expireAt
        Enabled: true
      TableName: "ConversationRelayAppDatabase"
      BillingMode: 'PAY_PER_REQUEST'
      AttributeDefinitions:
        -
          AttributeName: "pk"
          AttributeType: "S"
        -
          AttributeName: "sk"
          AttributeType: "S"
        -
          AttributeName: "pk1"
          AttributeType: "S"
        -
          AttributeName: "sk1"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "pk"
          KeyType: "HASH"
        -
          AttributeName: "sk"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        # String based index. Keys vary by type of item
        -
          IndexName: "index-1-full"
          KeySchema:
            -
              AttributeName: "pk1"
              KeyType: "HASH"
            -
              AttributeName: "sk1"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"

  ########################################
  # Lambda Layer available to all lambdas
  # This layer makes it easy to build
  # update expressions.
  ########################################
  ConversationRelayDynamoDBUtilLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ConversationRelayDynamoDBUtilLayer
      Description: Helper functions for DynamoDB
      ContentUri: layers/layer-cr-dynamodb-util/
      CompatibleRuntimes:
        - nodejs20.x
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

Outputs:
  DynamonDBTableName:
    Value: !Ref DDBTable
    Export:
      Name: 'CRPrimaryDynamoTableName'
  DynamonDBArn:
    Value: !GetAtt 
      - DDBTable
      - Arn
    Export:
      Name: 'CRPrimaryDynamoTableArn'